server:
  port: 8888

spring:
  application:
    name: springboot-redis
  redis:
    database: 0
    host: 192.168.2.20
    port: 6380
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    